using System;
using System.Drawing;
using System.Windows.Forms;
using Sistem_Bancar.DataAccess;

namespace Sistem_Bancar
{
    public class CreateAccountForm : Form
    {
        private TextBox txtUsername;
        private TextBox txtPassword;
        private TextBox txtConfirm;
        private Button btnCreate;
        private ComboBox cbRole;
        private Button btnCancel;

        public CreateAccountForm()
        {
            Text = "Create new account";
            Size = new Size(420, 300);
            FormBorderStyle = FormBorderStyle.FixedDialog;
            StartPosition = FormStartPosition.CenterParent;
            MaximizeBox = false;
            MinimizeBox = false;

            Label lblUser = new Label { Text = "Username", Left = 24, Top = 24, Width = 100 };
            txtUsername = new TextBox { Left = 24, Top = 48, Width = 340 };

            Label lblPass = new Label { Text = "Password", Left = 24, Top = 88, Width = 100 };
            txtPassword = new TextBox { Left = 24, Top = 112, Width = 340, UseSystemPasswordChar = true };

            Label lblConfirm = new Label { Text = "Confirm password", Left = 24, Top = 152, Width = 120 };
            txtConfirm = new TextBox { Left = 24, Top = 176, Width = 340, UseSystemPasswordChar = true };

            Label lblRole = new Label { Text = "Role", Left = 24, Top = 208, Width = 60 };
            cbRole = new ComboBox { Left = 80, Top = 204, Width = 140, DropDownStyle = ComboBoxStyle.DropDownList };
            cbRole.Items.AddRange(new[] { "Customer", "Employee" });
            cbRole.SelectedIndex = 0;

            btnCreate = new Button { Text = "Create account", Left = 240, Top = 204, Width = 120, BackColor = Color.FromArgb(0, 123, 255), ForeColor = Color.White, FlatStyle = FlatStyle.Flat };
            btnCreate.Click += BtnCreate_Click;

            btnCancel = new Button { Text = "Cancel", Left = 240, Top = 240, Width = 120 };
            btnCancel.Click += (s, e) => Close();

            Controls.AddRange(new Control[] { lblUser, txtUsername, lblPass, txtPassword, lblConfirm, txtConfirm, lblRole, cbRole, btnCreate, btnCancel });
        }

        private void BtnCreate_Click(object sender, EventArgs e)
        {
            string user = txtUsername.Text.Trim();
            string pass = txtPassword.Text;
            string confirm = txtConfirm.Text;
            string role = cbRole.SelectedItem.ToString();

            if (string.IsNullOrWhiteSpace(user) || string.IsNullOrWhiteSpace(pass))
            {
                MessageBox.Show("Please fill username and password", "Validation", MessageBoxButtons.OK, MessageBoxIcon.Warning);
                return;
            }

            if (pass != confirm)
            {
                MessageBox.Show("Passwords do not match", "Validation", MessageBoxButtons.OK, MessageBoxIcon.Warning);
                return;
            }

            try
            {
                var existing = Database.GetUserByUsername(user);
                if (existing != null)
                {
                    MessageBox.Show("Username already exists", "Validation", MessageBoxButtons.OK, MessageBoxIcon.Warning);
                    return;
                }

                // 
                int newId = Database.CreateUser(user, pass, role);
                if (newId > 0)
                {
                    string successMessage = "Account created successfully.";

                    // 
                    if (role == "Customer")
                    {
                        string autoGeneratedIban = Database.GenerateRandomIban();
                        Database.CreateBankAccount(newId, autoGeneratedIban, "Current");
                        successMessage += $"\n\nA default 'Current' account was created.\nYour IBAN is: {autoGeneratedIban}";
                    }

                    MessageBox.Show(successMessage, "Success", MessageBoxButtons.OK, MessageBoxIcon.Information);
                    Close();
                }
                else
                {
                    MessageBox.Show("Failed to create account", "Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
                }
            }
            catch (Exception ex)
            {
                MessageBox.Show("Database error: " + ex.Message, "Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
            }
        }
    }
    
}